,---
title: |
  | \vspace{4cm} \huge \textbf{ගිම්හානයේ මට හමු වූ}
  | \Huge \textbf{ජහිතා භවන්ති}
subtitle: |
  | \vspace{1cm} \large රතන සූත්‍රය ඇසුරින් පංච උපාදානස්කන්ධය පිළිබඳ 
  | ඉංජිනේරුමය සහ විදර්ශනාත්මක විග්‍රහයක්
author: |
  | \vspace{3cm} \Large \textbf{චින්තක දේශප්‍රිය ගුණදාස}
  | \small (Chief Technology Officer - Cybergate Services Private Limited)
date: "2026"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::pdf_book:
    latex_engine: xelatex
    toc: true
    toc_depth: 2
    keep_tex: yes
header-includes:
  - \usepackage{xcolor}
  - \usepackage{fontspec}
  - \setmainfont{Iskoola Pota} % ඔබගේ OS එකෙහි ඇති සිංහල ෆොන්ට් එක මෙහි සඳහන් කරන්න
  - \definecolor{darkblue}{HTML}{000033}
  - \definecolor{techblue}{HTML}{00CCFF}
  - \pagecolor{darkblue}
  - \color{white}
description: "රතන සූත්‍රය සහ පංච උපාදානස්කන්ධය පිළිබඳ ඉංජිනේරුමය විග්‍රහයක්."
---

# පෙරවදන {-}

\pagecolor{white}
\color{black}

මෙම කෘතිය ලියැවෙන්නේ වසර 25කට අධික කාලයක් තොරතුරු තාක්ෂණ ක්ෂේත්‍රයේ, විශේෂයෙන්ම Linux පද්ධති ඉංජිනේරු විද්‍යාව සහ ව්‍යවසාය මට්ටමේ දත්ත යටිතල පහසුකම් සමඟ මා ලැබූ අත්දැකීම් පදනම් කරගෙනය. 

බුදු දහමේ එන පංච උපාදානස්කන්ධ විග්‍රහය සහ රතන සූත්‍රයේ ගැඹුරු දහම් කරුණු, නවීන දත්ත සැකසීමේ ක්‍රියාවලියකට (Data Processing) සමාන කර බැලීම මෙහි මූලික අරමුණයි. අප ජීවිතයේ මුහුණ දෙන අටලෝ දහම නමැති ගිම්හානය මැද, සිත නමැති මෙහෙයුම් පද්ධතිය තුළ "ජහිතා භවන්ති" හෙවත් සැබෑ නිදහස අත්දකින්නේ කෙසේද යන්න මෙහිදී තාක්ෂණික උපමා ඇසුරින් සාකච්ඡා කෙරේ.

විද්‍යුත් හා යාන්ත්‍රික පද්ධතිවල පවතින නියතයන් මෙන්ම, සිත තුළ ක්‍රියාත්මක වන ත්‍රිලක්ෂණය නමැති නියතය හඳුනා ගැනීමෙන් ඕනෑම පීඩාකාරී පරිසරයක වුවද අකම්පිතව හිඳීමේ හැකියාව අපට ලැබේ. මෙම විග්‍රහය තාර්කික බුද්ධියෙන් යුතුව දහම විමසන නවීන පරපුරටත්, තාක්ෂණික ක්ෂේත්‍රයේ නියැලී සිටින වෘත්තිකයන්ටත් තම ආධ්‍යාත්මික ගමන සඳහා නව මාවතක් විවර කරනු ඇතැයි මම විශ්වාස කරමි.

\vspace{1.5cm}

**චින්තක දේශප්‍රිය ගුණදාස** Chief Technology Officer (CTO)  
Cybergate Services Private Limited  

\newpage
